# Generated by Django 4.2.23 on 2025-08-01 10:23

from django.db import migrations, models
import django.db.models.deletion
import month.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_type', models.CharField(choices=[('essencial', 'Essencial'), ('pessoal', 'Pessoal'), ('financeiro', 'Financeiro')], max_length=50)),
                ('categ_main_name', models.CharField(max_length=255)),
                ('categ_sub_name', models.CharField(max_length=255)),
                ('fixed_expense', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Categoria de Despesa',
                'verbose_name_plural': 'Categorias de Despesa',
                'unique_together': {('expense_type', 'categ_main_name', 'categ_sub_name')},
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('payer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('expense_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_date', models.DateField()),
                ('reference_month', month.models.MonthField(verbose_name='Mes da despesa')),
                ('description', models.CharField(max_length=255)),
                ('expense_location', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão', 'Cartão')], max_length=255)),
                ('in_installments', models.BooleanField(default=False)),
                ('installment_number', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='despesas.bank')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='despesas.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='despesas.owner')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='despesas.payer')),
            ],
        ),
    ]
